apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ui
  name: lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: ui
  type: LoadBalancer
status:
  loadBalancer: {}
